// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYJTHqUIBrknwWwuJ2BAEKnVf4NqPPOYw',
    appId: '1:10474039323:web:8dea60971eac1d4ea430be',
    messagingSenderId: '10474039323',
    projectId: 'casadienta-dental',
    authDomain: 'casadienta-dental.firebaseapp.com',
    storageBucket: 'casadienta-dental.appspot.com',
    measurementId: 'G-NHSL7ZKFK0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxEbEPWXGaW8sAIiypd1Kz5h0x9jslJdo',
    appId: '1:10474039323:android:09f364a27fba6651a430be',
    messagingSenderId: '10474039323',
    projectId: 'casadienta-dental',
    storageBucket: 'casadienta-dental.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMLjgit1CP-n1lqnUDsWkDOozAvNTAQJw',
    appId: '1:10474039323:ios:6610e8428fe6eeb1a430be',
    messagingSenderId: '10474039323',
    projectId: 'casadienta-dental',
    storageBucket: 'casadienta-dental.appspot.com',
    iosClientId: '10474039323-a25d1bq2pt6bt0s4gin4jdcor606cg3d.apps.googleusercontent.com',
    iosBundleId: 'com.example.ahliGigi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMLjgit1CP-n1lqnUDsWkDOozAvNTAQJw',
    appId: '1:10474039323:ios:6610e8428fe6eeb1a430be',
    messagingSenderId: '10474039323',
    projectId: 'casadienta-dental',
    storageBucket: 'casadienta-dental.appspot.com',
    iosClientId: '10474039323-a25d1bq2pt6bt0s4gin4jdcor606cg3d.apps.googleusercontent.com',
    iosBundleId: 'com.example.ahliGigi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYJTHqUIBrknwWwuJ2BAEKnVf4NqPPOYw',
    appId: '1:10474039323:web:64eb40ef521830d6a430be',
    messagingSenderId: '10474039323',
    projectId: 'casadienta-dental',
    authDomain: 'casadienta-dental.firebaseapp.com',
    storageBucket: 'casadienta-dental.appspot.com',
    measurementId: 'G-GV7MTCR8PL',
  );

}